### ISSUE TITLE
attributes not showing in battery segment

### ISSUE THREAD

**Issue by riemers** [pilotak/HomeAssistant-CustomComponents#2]
Something is not showing up and i don't know why.. i have my full list which is create by the attributes py. Which is:

![image](https://user-images.githubusercontent.com/682041/32420001-61c751c8-c284-11e7-8d45-77a65a4327cf.png)

In my config i have:
```
- platform: attributes
  attribute: battery_level
  unit_of_measurement: "%"
  entities:
    - zwave.thermostaat_lex
    - zwave.thermostaat_evi
    - zwave.thermostaat_erik
    - zwave.thermostaat_entree
    - zwave.thermostaat_vio
    - zwave.smoke_vio
    - zwave.smoke_lex
    - zwave.smoke_gang_bg
    - zwave.smoke_gang_2e
    - zwave.smoke_gang_1e
    - zwave.smoke_evi
    - zwave.smoke_eriks
    - zwave.smoke_entree
    - zwave.smoke_berging
    - zwave.slaapkamer_smoke
    - zwave.sensor_wc
    - zwave.motion_gang_2e
    - zwave.motion_gang_1e
    - zwave.motion_gang_begane_grond
    - zwave.motion_entree
    - zwave.motion_berging
    - zwave.keuken_deur
    - zwave.garage_buiten_deur
    - zwave.entree_deur
```

And in my top list i still have 2 sensors showing:

![image](https://user-images.githubusercontent.com/682041/32420023-bd15a39a-c284-11e7-9453-a4909694e173.png)

The names are zwave.motion_gang_begane_grond & zwave.thermostaat_vio but yet they are not shown. Even while these devices are the same devices i have in the list, its not in particular different hardware then the ones that do show.

I must be missing something stupid..
