### ISSUE TITLE
Use attributes.py to get last_updated ?

### ISSUE THREAD

**Issue by deveth0** [pilotak/HomeAssistant-CustomComponents#4]
Hi,
I'm currently looking for a way to get the "last_updated" date for each of my sensors. I'm already using your attributes.py (thanks btw!) to extract the battery_level but can't figure out, how to get the `last_updated` value. 
Most likely it does not work, because the `last_updated` value is saved as state and not attribute (?).
```
- platform: attributes
  friendly_name: "Last update"
  attribute: last_updated
  entities:
    - sensor.pressure_sensor_1_0
    - sensor.pressure_sensor_105_0
```

Do you seen any possibility to use your component to extract this value so I don't have to build a template for each sensor?

Thanks in advance
